<script setup>
  const tileUrl = 'https://demotiles.maplibre.org/tiles-omt/{z}/{x}/{y}.pbf';
  const gpxData = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Ink Capabilities Demo">
  <wpt lat="47.2690" lon="11.4036">
    <name>Start</name>
  </wpt>
  <wpt lat="47.2704" lon="11.4092">
    <name>Summit View</name>
  </wpt>
  <trk>
    <name>Innsbruck Old Town Loop</name>
    <trkseg>
      <trkpt lat="47.2690" lon="11.4036" />
      <trkpt lat="47.2692" lon="11.4044" />
      <trkpt lat="47.2695" lon="11.4058" />
      <trkpt lat="47.2699" lon="11.4071" />
      <trkpt lat="47.2704" lon="11.4092" />
      <trkpt lat="47.2698" lon="11.4099" />
      <trkpt lat="47.2689" lon="11.4087" />
      <trkpt lat="47.2685" lon="11.4068" />
      <trkpt lat="47.2686" lon="11.4052" />
      <trkpt lat="47.2690" lon="11.4036" />
    </trkseg>
  </trk>
</gpx>`;
  const gpxDocument = GPXDocument.from(gpxData);
  gpxDocument.addWaypoint({
    latitude: 47.2688,
    longitude: 11.4061,
    name: 'Coffee Stop'
  });
  const generatedGpxData = gpxDocument.toString();

  export default {
    data: {
      tileUrl,
      generatedGpxData
    },
    onLoad() {
      console.log('Map MVT page loaded');
    }
  };
</script>

<page>
  <view class="container">
    <view class="page-header">
      <text class="page-kicker">Mapbox Vector Tiles</text>
      <text class="title">MVT 地图渲染</text>
      <text class="subtitle">
        使用公开 MapLibre demo 矢量瓦片源，验证 map 组件的瓦片请求、MVT 解码和基础面线点渲染。
      </text>
    </view>

    <view class="panel">
      <view class="panel-heading">
        <text class="section-kicker">City Overview</text>
        <text class="section-title">Innsbruck 视图</text>
        <text class="section-note">zoom 12 会同时覆盖水体、道路、建筑和行政边界等常见 MVT 图层。</text>
      </view>
      <map
        class="map-surface map-surface-large"
        tile-url="{{ tileUrl }}"
        longitude="11.4041"
        latitude="47.2692"
        zoom="12"
      />
    </view>

    <view class="panel">
      <view class="panel-heading">
        <text class="section-kicker">Local Detail</text>
        <text class="section-title">同一瓦片源的更高缩放级别</text>
        <text class="section-note">第二张地图使用不同配色和 zoom 14，方便观察缓存、重绘和线宽变化。</text>
      </view>
      <map
        class="map-surface map-surface-small"
        tile-url="{{ tileUrl }}"
        longitude="11.4041"
        latitude="47.2692"
        zoom="14"
      />
    </view>

    <view class="panel">
      <view class="panel-heading">
        <text class="section-kicker">Overlay Demo</text>
        <text class="section-title">纯 GPX 容器地图</text>
        <text class="section-note">
          这个示例不声明 tile-url 和 lon/lat/zoom，仅通过 overlays slot 挂入 map-gpx，并根据 GPX bounds 自动 fit 视口。
        </text>
      </view>
      <view class="map-surface-frame map-surface-frame-circle">
        <map class="map-surface-circle">
          <template slot="overlays">
            <map-gpx
              data="{{ generatedGpxData }}"
              stroke-color="#2563eb"
              stroke-width="4"
              point-radius="4"
              waypoint-color="#0f172a"
              start-color="#16a34a"
              end-color="#dc2626"
              label-visible="true"
            />
          </template>
        </map>
      </view>
      <view class="meta-card">
        <text class="meta-title">GPX Source</text>
        <text class="meta-value">Generated by GPXDocument.from(...).addWaypoint(...).toString()</text>
      </view>
    </view>
  </view>
</page>

<style>
  .container {
    display: flex;
    flex-direction: column;
    width: 100%;
    padding: var(--spacing-lg, 20px);
    gap: var(--spacing-lg, 20px);
    box-sizing: border-box;
    background-color: var(--color-background);
  }

  .page-header {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .page-kicker,
  .section-kicker {
    font-size: 12px;
    color: var(--color-text-secondary);
  }

  .title {
    font-size: 28px;
    font-weight: bold;
    color: var(--color-text-primary);
  }

  .subtitle,
  .section-note {
    font-size: 14px;
    color: var(--color-text-secondary);
    line-height: 20px;
  }

  .panel {
    display: flex;
    flex-direction: column;
    gap: 12px;
    padding: var(--spacing-md, 16px);
    border-radius: var(--radius-sm, 8px);
    border: var(--border-width-thin, 1px) solid var(--border-color-default, #d5dadd);
    background-color: var(--color-surface);
  }

  .panel-heading {
    display: flex;
    flex-direction: column;
    gap: 5px;
  }

  .section-title {
    font-size: 18px;
    font-weight: 600;
    color: var(--color-text-primary);
  }

  .map-surface {
    width: 100%;
    border-radius: var(--radius-sm, 8px);
    overflow: hidden;
    background-color: var(--map-background, #eff4f1);
    border: 2px solid var(--border-color-default, #d5dadd);
  }

  .map-surface-large {
    height: 320px;
  }

  .map-surface-small {
    height: 220px;
  }

  .map-surface-circle {
    width: 100%;
    height: 100%;
    border-radius: 50% !important;
    border: 2px solid var(--border-color-default, #d5dadd);
  }

  .map-surface-frame-circle {
    width: 320px;
    height: 320px;
    align-self: center;
    border-radius: 160px;
    overflow: hidden;
    border: var(--border-width-thin, 1px) solid var(--border-color-default, #d5dadd);
    background-color: var(--map-background, #eff4f1);
  }

  .meta-card {
    display: flex;
    flex-direction: column;
    gap: 4px;
    padding: 10px 12px;
    border-radius: var(--radius-xs, 6px);
    background-color: var(--color-surface-secondary, rgba(0, 0, 0, 0.03));
  }

  .meta-title {
    font-size: 12px;
    color: var(--color-text-secondary);
  }

  .meta-value {
    font-size: 12px;
    color: var(--color-text-primary);
    line-height: 18px;
  }
</style>
